# Generated by codegen_tool

.PHONY: dclean drun dtest dcibuild dbash dmake

#DOCKER_IMAGE = registry.miranetworks.net/miranetworks/dev_ubuntu_trusty_erlang_17.4
DOCKER_IMAGE = mira_mochiweb
DOCKER_CONTAINER_NAME = $(DOCKER_IMAGE)

DOCKER_BUILT = docker/.Dockerfile.built




$(DOCKER_BUILT): docker/Dockerfile
	@docker build -t $(DOCKER_IMAGE) docker/ && touch $(DOCKER_BUILT)

dcibuild: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make test" true 

dtest: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make test suite=${suite}" false 

dclean: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make clean" true

ddockerclean: 
	@rm -f $(DOCKER_BUILT)

dmake: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make" false

drun: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make run" false

dbash: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "/bin/bash" false -t


