FROM registry.miranetworks.net/miranetworks/dev_ubuntu_trusty_erlang_17.4

#RUN apt-get update \
#    && DEBIAN_FRONTEND=noninteractive apt-get install -y libpam0g-dev \
#        unixodbc \
#        sqlite3 \
#        libsqliteodbc \
#        odbc-postgresql

