#!/bin/bash
WRKDIR=`readlink -f $(pwd)`
docker run --rm=true -i -u="developer" --name mochiweb -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(pwd)/../:/workspace/base mochiweb $1
docker rm -f mochiweb 2>/dev/null  || true
